# Prometheus configuration for OrderBook Data Collector
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # OrderBook Collector metrics
  - job_name: 'orderbook-collector'
    static_configs:
      - targets: ['collector:9091']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # API service metrics
  - job_name: 'orderbook-api'
    static_configs:
      - targets: ['api:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # PostgreSQL metrics (if exporter is configured)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s